camera:
  coordinates:
    area1:
      camara: Perforador
      height: 112.6984126984127
      punto: IESCO_T661_ECP
      width: 199.16391090035563
      x: 31.15679790353778
      y: 6.977513227513227
    area2:
      camara: Perforador
      height: 103.43915343915344
      punto: IESCO_T661_ECP
      width: 42.8277282086479
      x: 250.6863417982155
      y: 36.07804232804233
    area3:
      camara: Perforador
      height: 24.074074074074076
      punto: IESCO_T661_ECP
      width: 92.24433768016473
      x: 147.95969301803206
      y: 123.90873015873015
  info_emails: '["cristian.tascon@.com", "nelson.ceron@axuretechnologies.com"]'
  info_notifications: '{"Email": true, "Imagen": false, "Page_HSE": true, "Video":
    true}'
  ip: 10.10.138.232
  label: ''
  name camera: Perforador
  password: 4xUR3_2017
  place: POZO11
  point: IESCO_T661_ECP
  port: 554
  rtsp_url: rtsp://admin:4xUR3_2017@10.10.138.232:554/Streaming/Channels/102
  time_areas: '{"area1": "3", "area2": "10", "area3": "10"}'
  username: admin
labels:
- A_Person
- Harness
- No_Helmet
- White
- YellowGreen
model:
  path: models/juanmodelo.pt
