camera:
  coordinates:
    area1:
      A_Person: '99'
      No_Helmet: '12'
      camara: Mesa
      height: 146.805289189462
      punto: IESCO_T661_ECP
      width: 120.3942293958006
      x: 2.588201685473504
      y: 0.9727970122135864
    area2:
      White: '12'
      camara: Mesa
      height: 143.65600080750986
      punto: IESCO_T661_ECP
      width: 166.1934009427225
      x: 127.64462219682903
      y: 1.2150499646714443
  ip: 10.10.115.231
  label: null
  name camera: Mesa
  password: 4xUR3_2017
  place: POZO11
  point: IESCO_T661_ECP
  port: 554
  rtsp_url: rtsp://admin:4xUR3_2017@10.10.115.231:554/Streaming/Channels/102
  time_areas: '{"area1": "5", "area2": "7", "area3": "10"}'
  username: admin
labels:
- A_Person
- Harness
- No_Helmet
- White
- YellowGreen
model:
  path: models/juanmodelo.pt
