camera:
  coordinates:
    area1:
      Personas: '25'
      camara: Mesa
      height: 40.2116402116402
      punto: IESCO_T661_ECP
      width: 99.43220814874897
      x: 114.71579210082984
      y: 49.520502645502646
  ip: 10.10.115.231
  label: ',Harness, A_Person'
  name camera: Mesa
  password: 4xUR3_2017
  place: POZO11
  point: IESCO_T661_ECP
  port: 554
  rtsp_url: rtsp://admin:4xUR3_2017@10.10.115.231:554/Streaming/Channels/102
  username: admin
labels:
- A_Person
- Harness
- No_Helmet
- White
- YellowGreen
model:
  path: models/juanmodelo.pt
