camera:
  coordinates: '{"x": 71.64315500887596, "y": 31.396375990939976, "width": 171.42677072719823,
    "height": 89.80294450736127, "camara": "Mesa", "punto": "IESCO_T661_ECP"}'
  ip: 10.10.115.231
  label: ''
  name camera: Mesa
  password: 4xUR3_2017
  place: POZO11
  point: IESCO_T661_ECP
  port: 554
  probability: '10'
  rtsp_url: rtsp://admin:4xUR3_2017@10.10.115.231:554/Streaming/Channels/102
  username: admin
labels:
- A_Person
- Harness
- No_Helmet
- White
- YellowGreen
model:
  path: models/juanmodelo.pt
