camera:
  coordinates:
    area1:
      A_Person: '10'
      camara: Perforador
      height: 143.17149490259413
      punto: IESCO_T661_ECP
      width: 183.47093272389657
      x: 112.2868161691187
      y: 2.1840617745028768
    area2:
      A_Person: '10'
      camara: Perforador
      height: 144.38275966488342
      punto: IESCO_T661_ECP
      width: 106.13340951292673
      x: 0.313955149264391
      y: 0.1840617745028768
  ip: 10.10.115.232
  label: A_Person
  name camera: Perforador
  password: 4xUR3_2017
  place: POZO11
  point: IESCO_T661_ECP
  port: 554
  rtsp_url: rtsp://admin:4xUR3_2017@10.10.115.232:554/Streaming/Channels/102
  time_areas: '{"area1": "50", "area2": "80", "area3":"30"}'
  username: admin
labels:
- A_Person
- Harness
- No_Helmet
- White
- YellowGreen
model:
  path: models/juanmodelo.pt
