camera:
  # URL completa con usuario y contraseña
  rtsp_url: "rtsp://admin:4xUR3_2017@10.10.115.231:554/Streaming/Channels/102"

  # Parámetros separados por si necesitas construir la URL dinámicamente
  username: "admin"
  password: "4xUR3_2017"
  ip: "10.10.115.231"
  port: 554
  stream_path: "/Streaming/Channels/102"  # Ruta del stream

model:
  path: "models/juanmodelo.pt"  # Ruta al modelo YOLO

# labels:
#   - person
#   # - car
#   # - bicycle
#   # - dog
