camera:
  coordinates: '{"x": 91.81101038854634, "y": 46.617214043035105, "width": 85.51170680980242,
    "height": 75.23442808607022, "camara": "Mesa", "punto": "IESCO_T661_ECP"}'
  ip: 10.10.115.231
  label: ',Harness, A_Person'
  name camera: Mesa
  password: 4xUR3_2017
  place: POZO11
  point: IESCO_T661_ECP
  port: 554
  probability: '68'
  rtsp_url: rtsp://admin:4xUR3_2017@10.10.115.231:554/Streaming/Channels/102
  username: admin
labels:
- A_Person
- Harness
- No_Helmet
- White
- YellowGreen
model:
  path: models/juanmodelo.pt
