camera:
  coordinates:
    area1:
      camara: Mesa
      height: 139.94708994708995
      punto: IESCO_T661_ECP
      width: 107.2190678230486
      x: 5.6997566606351775
      y: 2.69510582010582
    area2:
      camara: Mesa
      height: 139.41798941798942
      punto: IESCO_T661_ECP
      width: 78.46758594871153
      x: 117.71073812940662
      y: 2.69510582010582
  info_notifications: '{"Email": false, "Imagen": true, "Page_HSE": true, "Video":
    false}'
  ip: 10.10.115.231
  label: ''
  name camera: Mesa
  password: 4xUR3_2017
  place: POZO11
  point: IESCO_T661_ECP
  port: 554
  rtsp_url: rtsp://admin:4xUR3_2017@10.10.115.231:554/Streaming/Channels/102
  time_areas: '{"area1": "1", "area2": "9", "area3": "10"}'
  username: admin
labels:
- A_Person
- Harness
- No_Helmet
- White
- YellowGreen
model:
  path: models/juanmodelo.pt
