camera:
  coordinates:
    area1:
      A_Person: '50'
      Harness: '10'
      camara: Mesa
      height: 75.23442808607022
      punto: IESCO_T661_ECP
      width: 85.51170680980242
      x: 91.81101038854634
      y: 46.617214043035105
    area2:
      A_Person: '50'
      Harness: '10'
      No_Helmet: '20'
      camara: Mesa
      height: 75.23442808607022
      punto: IESCO_T661_ECP
      width: 85.51170680980242
      x: 91.81101038854634
      y: 46.617214043035105
  ip: 10.10.115.232
  label: ',No_Helmet,White,YellowGreen, A_Person'
  name camera: Perforador
  password: 4xUR3_2017
  place: POZO11
  point: IESCO_T661_ECP
  port: 554
  rtsp_url: rtsp://admin:4xUR3_2017@10.10.115.232:554/Streaming/Channels/102
  username: admin
labels:
- A_Person
- Harness
- No_Helmet
- White
- YellowGreen
model:
  path: models/juanmodelo.pt
