camera:
  coordinates:
    ? ''
    : ? ''
      : '10'
    area1:
      A_Person: '10'
      camara: Perforador
      height: 147.88359788359787
      punto: IESCO_T661_ECP
      width: 150.04679603169652
      x: 1.207337617770013
      y: 1.6369047619047619
    area2:
      A_Person: '10'
      camara: Perforador
      height: 147.88359788359787
      punto: IESCO_T661_ECP
      width: 143.7574093716853
      x: 153.9495850751856
      y: 1.6369047619047619
  ip: 10.10.115.232
  label: ''
  name camera: Perforador
  password: 4xUR3_2017
  place: POZO11
  point: IESCO_T661_ECP
  port: 554
  rtsp_url: rtsp://admin:4xUR3_2017@10.10.115.232:554/Streaming/Channels/102
  time_areas: '{"area1": "10", "area2": "10", "area3": "10"}'
  username: admin
labels:
- A_Person
- Harness
- No_Helmet
- White
- YellowGreen
model:
  path: models/juanmodelo.pt
