camera:
  coordinates:
    area1:
      Personas: '25'
      camara: Perforador
      height: 139.41798941798942
      punto: IESCO_T661_ECP
      width: 277.33200224620947
      x: 13.486616334934796
      y: 5.340608465608465
  ip: 10.10.115.232
  label: ',No_Helmet,White,YellowGreen, A_Person'
  name camera: Perforador
  password: 4xUR3_2017
  place: POZO11
  point: IESCO_T661_ECP
  port: 554
  rtsp_url: rtsp://admin:4xUR3_2017@10.10.115.232:554/Streaming/Channels/102
  username: admin
labels:
- A_Person
- Harness
- No_Helmet
- White
- YellowGreen
model:
  path: models/juanmodelo.pt
