camera:
  coordinates:
    area1:
      camara: Perforador
      height: 20.1058201058201
      punto: IESCO_T661_ECP
      width: 24.25906283147191
      x: 137.776876520871
      y: 57.45701058201058
  ip: 10.10.115.232
  label: ',No_Helmet,White,YellowGreen, A_Person'
  name camera: Perforador
  password: 4xUR3_2017
  place: POZO11
  point: IESCO_T661_ECP
  port: 554
  rtsp_url: rtsp://admin:4xUR3_2017@10.10.115.232:554/Streaming/Channels/102
  username: admin
labels:
- A_Person
- Harness
- No_Helmet
- White
- YellowGreen
model:
  path: models/juanmodelo.pt
