camera:
  coordinates:
    area1:
      A_Person: '30'
      camara: Planchada
      points:
      - x: 174.7644599737942
        y: 62.2933201058201
      - x: 63.05297310788045
        y: 135.3091931216931
      - x: 187.64272789667436
        y: 146.68485449735448
      - x: 225.07955325388406
        y: 72.87533068783068
      - x: 175.0639545766519
        y: 62.2933201058201
      punto: TORITO_OESTE1_GEOPARK
  info_emails: '["nelson.ceron@axuretechnologies.com", "carlos.saavedra@axuretechnologies.com",
    "cristian.tascon@axuretechnologies.com", "fabismartinez867@gmail.com", "edwin.granados@axuretechnologies.com",
    "co.perforacion_07@geo-park.com", "taladrohs7@geo-park.com", "ygonzalez@geo-park.com",
    "vvalencia@geo-park.com", "fpuentes@geo-park.com", "edson.delgado@axuretechnologies.com"]'
  info_notifications: '{"Email": true, "Imagen": true, "Page_HSE": true, "Video":
    false}'
  ip: 172.29.5.231
  label: A_Person, Loading_Machine
  name camera: Planchada
  password: 4xUR3_2017
  place: POZO11
  point: TORITO_OESTE1_GEOPARK
  port: 554
  rtsp_url: VideosEnsayoModelo/prueba_realizada_mesa.avi
  time_areas: '{"area1": "60", "area2": "60", "area3": "60"}'
  username: admin
labels:
- A_Person
- Harness
- No_Helmet
- White
- YellowGreen
model:
  path: models/best_mejorado.pt
