camera:
  coordinates:
    area1:
      camara: Perforador
      height: 139.41798941798942
      punto: IESCO_T661_ECP
      width: 267.14918574904846
      x: 7.197229674923566
      y: 4.546957671957672
  info_emails: '[]'
  info_notifications: '{"Email": true, "Imagen": false, "Page_HSE": true, "Video":
    true}'
  ip: 10.10.138.232
  label: ''
  name camera: Perforador
  password: 4xUR3_2017
  place: POZO11
  point: IESCO_T661_ECP
  port: 554
  rtsp_url: rtsp://admin:4xUR3_2017@10.10.138.232:554/Streaming/Channels/102
  time_areas: '{"area1": "3", "area2": "10", "area3": "10"}'
  username: admin
labels:
- A_Person
- Harness
- No_Helmet
- White
- YellowGreen
model:
  path: models/juanmodelo.pt
