camera:
  coordinates:
    area1:
      A_Person: '20'
      camara: Mesa
      height: 132.8042328042328
      punto: IESCO_T661_ECP
      width: 278.23048605478255
      x: 10.49167030635802
      y: 4.811507936507936
  info_emails: '["edwin.granados@axuretechnologies.com", "cristian.tascon@axuretechnologies.com",
    "nelson.ceron@axuretechnologies.com"]'
  info_notifications: '{"Email": true, "Imagen": false, "Page_HSE": true, "Video":
    true}'
  ip: 10.10.138.231
  label: A_Person
  name camera: Mesa
  password: 4xUR3_2017
  place: POZO11
  point: IESCO_T661_ECP
  port: 554
  rtsp_url: rtsp://admin:4xUR3_2017@10.10.138.231:554/Streaming/Channels/102
  time_areas: '{"area1": "3", "area2": "10", "area3": "10"}'
  username: admin
labels:
- A_Person
- Harness
- No_Helmet
- White
- YellowGreen
model:
  path: models/juanmodelo.pt
