camera:
  coordinates:
    area1:
      Personas: '46'
      camara: Mesa
      height: 141.53439153439152
      punto: IESCO_T661_ECP
      width: 287.51481874337054
      x: 6.598240469208211
      y: 3.224206349206349
  ip: 10.10.115.231
  label: ',Harness, A_Person'
  name camera: Mesa
  password: 4xUR3_2017
  place: POZO11
  point: IESCO_T661_ECP
  port: 554
  rtsp_url: rtsp://admin:4xUR3_2017@10.10.115.231:554/Streaming/Channels/102
  username: admin
labels:
- A_Person
- Harness
- No_Helmet
- White
- YellowGreen
model:
  path: models/juanmodelo.pt
