camera:
  coordinates:
    area1:
      A_Person: '12'
      camara: Mesa1
      height: 142.03586929817376
      punto: IESCO_T661_ECP
      width: 105.91016548463355
      x: 4.13479812728874
      y: 2.1415117516992876
    area2:
      YellowGreen: '12'
      camara: Mesa1
      height: 138.36704610597002
      punto: IESCO_T661_ECP
      width: 82.47346219811803
      x: 117.7583089973578
      y: 3.975923347801163
    area3:
      White: '12'
      camara: Mesa1
      height: 143.87028089427565
      punto: IESCO_T661_ECP
      width: 91.96681036480783
      x: 204.97844527882074
      y: 3.189746949471788
  info_emails: '["xsd<aSA", "rhrthrhrhrh"]'
  info_notifications: '{"Email": false, "Imagen": true, "Page_HSE": true, "Video":
    false}'
  ip: 10.10.138.231
  label: A_Person,YellowGreen,White
  name camera: Mesa1
  password: 4xUR3_2017
  place: POZO11
  point: IESCO_T661_ECP
  port: 554
  rtsp_url: rtsp://admin:4xUR3_2017@10.10.138.231:554/Streaming/Channels/102
  time_areas: '{"area1": "3", "area2": "5", "area3": "6"}'
  username: admin
labels:
- A_Person
- Harness
- No_Helmet
- White
- YellowGreen
model:
  path: models/juanmodelo.pt
