camera:
  coordinates:
    area1:
      A_Person: '8'
      camara: Perforador
      height: 148.94179894179894
      punto: IESCO_T661_ECP
      width: 8.385848880014974
      x: 0.3088538091969801
      y: 0.31415343915343913
    area2:
      A_Person: '11'
      camara: Perforador
      height: 147.35449735449737
      punto: IESCO_T661_ECP
      width: 286.01734572908214
      x: 11.090659512073376
      y: 0.5787037037037037
  info_notifications: null
  ip: 10.10.115.232
  label: A_Person
  name camera: Perforador
  password: 4xUR3_2017
  place: POZO11
  point: IESCO_T661_ECP
  port: 554
  rtsp_url: rtsp://admin:4xUR3_2017@10.10.115.232:554/Streaming/Channels/102
  time_areas: '{"area1": 5, "area2": "10", "area3": "10"}'
  username: admin
labels:
- A_Person
- Harness
- No_Helmet
- White
- YellowGreen
model:
  path: models/juanmodelo.pt
