camera:
  coordinates:
    area1:
      A_Person: '20'
      Load_Machine: '40'
      camara: Planchada
      points:
      - x: 182.25182504523616
        y: 62.55787037037037
      - x: 95.39839021650964
        y: 127.90178571428571
      - x: 169.6730517252137
        y: 147.4785052910053
      - x: 216.39420977101142
        y: 70.22982804232804
      - x: 182.85081425095152
        y: 62.55787037037037
      punto: TORITO_OESTE1_GEOPARK
  info_emails: '["nelson.ceron@axuretechnologies.com","cristian.tascon@axuretechnologies.com",
    "fabianmartinezr867@gmail.com", "edwin.granados@axuretechnologies.com", "carlos.saavedra@axuretechnologies.com"]'
  info_notifications: '{"Email": true, "Imagen": false, "Page_HSE": true, "Video":
    true}'
  ip: 172.29.5.231
  label: A_Person, Loading_Machine
  name camera: Planchada
  password: 4xUR3_2017
  place: GEOPARK
  point: TORITO_OESTE1_GEOPARK
  port: 554
  rtsp_url: rtsp://admin:4xUR3_2017@172.29.5.231:554/Streaming/Channels/102
  time_areas: '{"area1": "100", "area2": "10", "area3": "10"}'
  username: admin
labels:
- A_Person
- Harness
- No_Helmet
- White
- YellowGreen
model:
  path: models/best_mejorado.pt
