camera:
  coordinates:
    area1:
      camara: Mesa
      height: 144.7089947089947
      punto: IESCO_T661_ECP
      width: 104.5236163973295
      x: 1.5068322206276907
      y: 2.1660052910052907
    area3:
      No_Helmet: '7'
      camara: Mesa
      height: 146.56084656084656
      punto: IESCO_T661_ECP
      width: 97.33574592874524
      x: 198.57428090097957
      y: 1.1078042328042328
  ip: 10.10.115.231
  label: ',A_Person,No_Helmet,White,YellowGreen'
  name camera: Mesa
  password: 4xUR3_2017
  place: POZO11
  point: IESCO_T661_ECP
  port: 554
  rtsp_url: rtsp://admin:4xUR3_2017@10.10.115.231:554/Streaming/Channels/102
  username: admin
labels:
- A_Person
- Harness
- No_Helmet
- White
- YellowGreen
model:
  path: models/juanmodelo.pt
