camera:
  coordinates:
    area1:
      A_Person: '39'
      camara: Planchada
      points:
      - x: 172.78684736138393
        y: 58.419118719197456
      - x: 67.24880738185239
        y: 139.04668863550202
      - x: 185.7810204519569
        y: 148.56522119506576
      - x: 230.15136759049867
        y: 70.4572628386457
      - x: 173.4207094633631
        y: 59.258989239158964
      punto: TORITO_OESTE1_GEOPARK
  info_emails: '[]'
  info_notifications: '{"Email": false, "Imagen": false, "Page_HSE": true, "Video":
    true}'
  ip: 172.29.5.231
  label: A_Person, Loading_Machine
  name camera: Planchada
  password: 4xUR3_2017
  place: POZO11
  point: TORITO_OESTE1_GEOPARK
  port: 554
  rtsp_url: rtsp://admin:4xUR3_2017@172.29.5.231:554/Streaming/Channels/102
  time_areas: '{"area1": "20", "area2": "60", "area3": "60"}'
  username: admin
labels:
- A_Person
- Harness
- No_Helmet
- White
- YellowGreen
model:
  path: models/best_ultimo.pt
