camera:
  coordinates:
    area1:
      A_Person: '10'
      camara: Perforador
      height: 147.0899470899471
      punto: IESCO_T661_ECP
      width: 108.11755163162164
      x: -0.2901353965183752
      y: 1.1078042328042328
    area2:
      A_Person: '10'
      camara: Perforador
      height: 147.0899470899471
      punto: IESCO_T661_ECP
      width: 187.18412678604852
      x: 109.923878455107
      y: 0.31415343915343913
  info_notifications: null
  ip: 10.10.115.232
  label: A_Person
  name camera: Perforador
  password: 4xUR3_2017
  place: POZO11
  point: IESCO_T661_ECP
  port: 554
  rtsp_url: rtsp://admin:4xUR3_2017@10.10.115.232:554/Streaming/Channels/102
  time_areas: '{"area1": "10", "area2": "5", "area3": "10"}'
  username: admin
labels:
- A_Person
- Harness
- No_Helmet
- White
- YellowGreen
model:
  path: models/juanmodelo.pt
