database:
  host: "10.20.30.33"
  port: 3306
  user: "ax_monitor"
  password: "axure.2024"
  database_name: "hseVideoAnalytics"
  query_yaml: "SELECT ID, LUGAR, PUNTO, NOMBRE_CAMARA, IP_CAMARA, USUARIO, CONTRASENA, ESTADO_LUGAR_MODELO, COORDENADAS_AREA, TIME_AREAS, INFO_NOTIFICATIONS, DESTINATARIOS FROM IP_Videofeed2;"
  query_json: "SELECT * FROM IP_Videofeed2;"

